version: "3.5"

services:
    database:
      image: postgres:latest
      restart: on-failure
      volumes:
        - pg_data:/var/lib/postgresql/data:cached
        - ./docker/postgres/records.sql:/docker-entrypoint-initdb.d/records.sql
      ports:
        - 5432
      environment:
        PGDATA: /var/lib/postgresql/data/pgdata
        POSTGRES_DB: dev
        POSTGRES_PASSWORD: dev

    web:
      image: nginx:alpine
      restart: on-failure
      volumes:
        - ./public:/app/public:cached
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 1313:80

    app:
      build: docker/php-fpm
      restart: on-failure
      working_dir: /app
      links:
        - database
      volumes:
        - .:/app:rw,cached
        - app_sessions_data:/var/php/sessions
        - composer_data:/home/www-data/.composer/cache
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

volumes:
  pg_data:
  app_sessions_data:
  composer_data:
